### ISSUE TITLE
ng-repeat not working inside template

### ISSUE THREAD

**Issue by furst** [Wildhoney/ngContextMenu#12]
The ng-repeat directive seems to be broken inside a partial. I know I have access to an array inside the partial but ng-repeat is not doing anything.

Any ideas?

**Comment by Wildhoney** [comment]
Good find &ndash; `ng-repeat` works from what I see, but the `x` in `ng-repeat="x in y"` wouldn't be interpolated correctly and would thus be `undefined`. Should be fixed now with `v0.3.3` :+1: Please try.

**Comment by furst** [comment]
Works great! Thanks for a quick fix!

**Comment by Wildhoney** [comment]
:+1:
