### ISSUE TITLE
Does it work with angular 1.3.16?

### ISSUE THREAD

**Issue by ibrahimmumcu** [Wildhoney/ngContextMenu#16]
My project is running on angular 1.3.16 and your module is not working (or I couldn't use properly). The project that I've been working on is a large application and I cannot change angular version. How can I use this module with 1.3.16 and at least which version angular should I use to install this module properly?

Thanks.

**Comment by Wildhoney** [comment]
I think in earlier versions you might have issues with [`$templateRequest`](https://github.com/Wildhoney/ngContextMenu/blob/master/module/ngContextMenu.js#L38) which was changed in the [following pull request](https://github.com/Wildhoney/ngContextMenu/pull/14) &ndash; we could revert this change to support more versions of Angular.

Thoughts?

**Comment by ibrahimmumcu** [comment]
Ok, I'll try changing these lines in that pull request.

**Comment by Wildhoney** [comment]
If that fixes things, please open another PR to revert it @ibrahimmumcu :+1: I think wider support is more important than *supporting* [https://www.npmjs.com/package/html2js](html2js).

When I merged that PR, I didn't realise `$templateRequest` was a `>=1.4.x` introduction.

**Comment by Wildhoney** [comment]
Also, if you open a PR for this, please then change the Angular dependency to be `>=1.3.0` in the [`package.json`](https://github.com/Wildhoney/ngContextMenu/blob/master/bower.json#L19).

**Comment by ibrahimmumcu** [comment]
While I was trying another problem came up. It's not related your module I just want to say that I cannot test what we're talking about.

I'm using grunt angular templates module. This module removing all html files and concating in a js file with angular $templateCache method. Your module is trying to get .html file with http request. I'm getting 404 error. Just saying to let you know,

Thanks.

**Comment by Wildhoney** [comment]
I think in this case `$templateRequest` might help, because it interrogates the `$templateCache` first. Although I wonder how this differs from providing `cache: $templateCache` as part of the `$http` request. I'd be interested to see if that solves your issue, whilst still maintaining support for your Grunt task.

```javascript
$http.get(attributes.contextMenu, { cache: $templateCache }).then(response => // ...)
```

**Comment by ibrahimmumcu** [comment]
Like I said before the problem is observing while getting template with http request. I should use $templateCache.get method to get file from cache. 

So I changed this lines to:
```$templateRequest(attributes.contextMenu).then(function then(response) {
	var compiled     = $compile(response)($angular.extend(getModel())),
		menu         = $angular.element(compiled);

	// Determine whether to append new, or replace an existing.
	switch (strategy) {
		case ('append'): element.append(menu); break;
		default: scope.menu.replaceWith(menu); break;
	}

	menu.css({

		position: 'fixed',
		top: 0,
		left: 0,
		transform: $interpolate('translate({{x}}px, {{y}}px)')({
			x: scope.position.x, y: scope.position.y
		})

	});

	scope.menu = menu;
	scope.menu.bind('click', closeMenu);

});```

to
```var response = $templateCache.get(attributes.contextMenu),
	compiled     = $compile(response)($angular.extend(getModel())),
	menu         = $angular.element(compiled);

// Determine whether to append new, or replace an existing.
switch (strategy) {
	case ('append'): element.append(menu); break;
	default: scope.menu.replaceWith(menu); break;
}

menu.css({
	position: 'fixed',
	top: 0,
	left: 0,
	display: 'block',
	transform: $interpolate('translate({{x}}px, {{y}}px)')({
		x: scope.position.x, y: scope.position.y
	})
});

scope.menu = menu;
scope.menu.bind('click', closeMenu);```

And it's worked!

I didn't find the successCallback for $templateCache.get method. It's may cause a problem if it's working asynchronously.
