### ISSUE TITLE
HTML element disappears from DOM after adding data-context-menu

### ISSUE THREAD

**Issue by ndjordjevic** [Wildhoney/ngContextMenu#20]
Hi,

I've something like this in one of my templates:

```<h2 data-context-menu="user.html">Hello2</h2>```

The h2 element is completely disappeared from DOM after the page is loaded. No errors in console, no idea what's wrong. I'm using angular 1.4.9. I've tried to add data-context-event="contextmenu" but it's the same.

**Comment by ndjordjevic** [comment]
It was my fault. Somewhere there was already a custom directive with the same name as yours :)

**Comment by Wildhoney** [comment]
Ah... coincidence. Phew!
