### ISSUE TITLE
Possible to pass variable to context-menu?

### ISSUE THREAD

**Issue by RicardoVaranda** [Wildhoney/ngContextMenu#23]
Hey everyone, I'm trying to access a vApp object within the data-context-menu

**index.html**
```
<div class="panel-body" ng-cloak>
      <a ng-repeat="vApp in vApps">
             <div class="col-sm-4"  data-context-menu="../context-menus/vapp.html">
                <div class="panel panel-primary" ng-click="getVApp(vApp.id)">
                      <div class="panel-heading"><h3>{{vApp.name}}</h3></div>
                </div>
            </div>
       </a>
</div>
```

**/context-menus/vapp.html**
```
<nav id="context-menu" class="context-menu">
    <ul class="context-menu__items">
        <li class="context-menu__item">
            <a class="context-menu__link" ng-click="power('on', vApp.href)">
                <i class="fa fa-eye"></i> Power On
            </a>
        </li>
        <li class="context-menu__item">
            <a class="context-menu__link" ng-click="power('off', vApp.href)">
                <i class="fa fa-edit"></i> Power Off
            </a>
        </li>
    </ul>
</nav>
```

The issue is even tho the data-context-menu is within the loop which has access to the vApp object because it is being called from an external source, is there a work around for this? Wether it be localy declaring the <nav id="context-menu" class="context-menu"> in the main index itself.

Thank you for your time.

**Comment by RicardoVaranda** [comment]
@Wildhoney , would you mind taking a look at this issue for me, thank you mate.

**Comment by Wildhoney** [comment]
[See example](https://github.com/Wildhoney/ngContextMenu/blob/master/example/index.html#L27).

You need to pass in `vApp` via the `ng-model` attribute on your `<a />` node &mdash; from within the associated HTML context menu you will have access to the model's properties.
