### ISSUE TITLE
Scroll issue

### ISSUE THREAD

**Issue by dieffrei** [Wildhoney/ngContextMenu#30]
When the page is scrolled the location doesnt match.
Change Line 123: scope.position = { x: event.pageX, y: event.pageY };
to scope.position = { x: event.clientX, y: event.clientY };

**Comment by kstefanini** [comment]
I have the same issue. 
Had to change ```fixed``` to ```absolute``` in :
```js
menu.css({
    position: 'fixed',
    top: 0,
    left: 0,
    transform: $interpolate('translate({{x}}px, {{y}}px)')({
        x: scope.position.x, y: scope.position.y
    })
});
```

**Comment by piotrgolasz** [comment]
Thanks! This issue can be closed now ;)
