### ISSUE TITLE
Context menu disappears instantly with Firefox

### ISSUE THREAD

**Issue by kstefanini** [Wildhoney/ngContextMenu#31]
Hello, I have this strange behavior with Firefox (not with Chrome) : context menu disapears instantly, unless I keep right click pressed and move cursor outside the element.

You can reproduce this on https://ng-contextmenu.herokuapp.com by disabling ```*```'s margin property.
I tried to add this property to my own css, but it doesn't work.

What have I missed?

**Comment by Wildhoney** [comment]
It was caused [by the offset](https://github.com/Wildhoney/ngContextMenu/blob/v0.7.0/module/ngContextMenu.js#L149). Deducting 1 from both `x` and `y` seems to solve the issue 👍 

Released fix as `v0.7.1`.

**Comment by Wildhoney** [comment]
Well, will hopefully be released once my `npm publish` works &ndash; [npm](http://status.npmjs.org/) seems to be having issues at the moment.

**Comment by Wildhoney** [comment]
Done 👍 Please re-open if the problems persists. Thanks!

**Comment by kstefanini** [comment]
Thanks for your quick reply! I've test this fix and deducting 1 is not enough in my case i have to deduct 3. Strange, isn't it?

**Comment by Wildhoney** [comment]
Hmm I think if it's any greater than 1 then that could be down to your CSS &ndash; I'd be against setting an arbitrary offset without an explanation as to the cause.

Is [the example](http://ng-contextmenu.herokuapp.com/) in Firefox still broken for you? As it works for me.

**Comment by kstefanini** [comment]
Yes, after disabling ```*```'s margin property the example is still broken. I don't understand how it can be associated.

**Comment by Wildhoney** [comment]
I've pushed `v.0.7.2` which should hopefully fix it for you. I needed to detect whether the click was indeed a left click, otherwise the menu is closed immediately.

**Comment by kstefanini** [comment]
It works! Thanks a lot :+1: 
(but build failed, example displays Application Error)

**Comment by Wildhoney** [comment]
Thanks 👍 I'll check Heroku.
