### ISSUE TITLE
Install seems to rely on bower / angular / grunt being installed

### ISSUE THREAD

**Issue by theashguy** [Wildhoney/ngContextMenu#33]
First up, I've used this lib before-- great work. Really easy to integrate and nice to work with.

Our business has moved on from bower and grunt, streamlining down to npm only and using gulp for our build pipeline instead. For some reason your npm package is attempting to run a bower install, and then a grunt install. Also I think it seems to be pulling angular through bower for testing? This is all causing my npm install to fail completely.

Seems like a pretty hectic dependency chain for such a tight little lib! Still debugging to see if there is anything obvious I can do, but it would be nice to get this cleaned up :).

**Comment by Wildhoney** [comment]
Agreed &ndash; we don't need the [`postinstall`](https://github.com/Wildhoney/ngContextMenu/blob/master/package.json#L10) as that was only ever used for the example, and there are better ways to do that using the `.travis.yml` file.

**Comment by Wildhoney** [comment]
Removed `postinstall` and pushed as `v.0.7.3` &ndash; I'll fix the example a little later when I have more time 👍
