### ISSUE TITLE
Menu stays open 

### ISSUE THREAD

**Issue by GrandLX** [Wildhoney/ngContextMenu#36]
Hi,

I recently had an issue, where the menu stays persistent on the screen. This was related to an ng-repeat in angular. It seems when angular removes the elements it also removes the controller of each context-menu-instance and the close-event has no more abilty to close the menu.

In my case i added another listener to the $destroy event and hooked it up to your close-method. This helped me out and everytime the pagination forces a change in the shown elements, each context-menu gets it's destroy-event and can close if it's open.

Perhaps this is an additional event, you can include?

**Comment by Wildhoney** [comment]
Could you please open a pull request for this? That'd be awesome 👍

**Comment by WeeJeWel** [comment]
@GrandLX I'm running into the same problem. Can you share the code for your solution? I'd gladly make a PR as well.

**Comment by GrandLX** [comment]
Added a PR for this #37

**Comment by Wildhoney** [comment]
Thanks folks &ndash; PR #37 merged and released as `v0.8.0`. Hopefully this is the end of the `ng-repeat` woes.

**Comment by WeeJeWel** [comment]
Thank you!
