### ISSUE TITLE
Context click triggers ng-click

### ISSUE THREAD

**Issue by falconfalc** [Wildhoney/ngContextMenu#38]
I have this issue in an ng-repeat where context menu is set on right-click and on ng-click i need other action. Right click event triggers ng-click also.

**Comment by Wildhoney** [comment]
I'm not sure I follow &mdash; context clicking on your element opens the menu, as expected, but then you want an `ng-click`?

**Comment by falconfalc** [comment]
Context menu is triggered but ng-click is triggered also in the same event.

**Comment by Wildhoney** [comment]
That's expected, as `ng-click` (and native `onclick`) don't distinguish between *types* of clicks. Instead you'll need to inspect `event.which` in your `ng-click` event to determine if the click was in fact a left click.

See: https://api.jquery.com/event.which/

**Comment by falconfalc** [comment]
I've tried this before opening the issue but, strangely, event.which is always 1.

**Comment by Wildhoney** [comment]
Are you using <kbd>option</kbd>/<kbd>ctrl</kbd>? As then you'll need to also detect `event.ctrlKey`.

**Comment by falconfalc** [comment]
No, just normal right-click.

**Comment by Wildhoney** [comment]
What was the resolution?

**Comment by falconfalc** [comment]
I've noticed that whenever I change the behaviour of right click with a directive, so instead of default browser's menu i do something custom, the left click is also triggered. At the moment it seems it's not strictly related to ngContextMenu.
