### ISSUE TITLE
Can I choose the parent container/div to be appended for the context menu?

### ISSUE THREAD

**Issue by neesonqk** [Wildhoney/ngContextMenu#39]
I noticed that my context menu is appended to `body` element, however, my sub-controller is attached to a child `div` of `body` element which made my context menu cannot interactive with my controller actions.

```html
<body>
    <div ng-controller='MyCtrl as ctrl'>....</div>
    ....
    <ContextMenu>....</ContextMenu>
</body>
```

**Comment by neesonqk** [comment]
I realized that only if the context menu was loaded from an external independent file then what I described never applies, but once I defined the context menu into a `text/ng-template` the menu would never get a chance to communicate with the controller.

**Comment by Wildhoney** [comment]
Did you find a workaround?

**Comment by neesonqk** [comment]
@Wildhoney thanks.

My problem was regardless ContextMenu, I remember I'd tested that even ContextMenu was appended to `body`, however, the `$scope` from parents will be passed over, so there is no problem with controller interaction.

my problem was something else which somehow I didn't handle the parents `$scope` properly.
