### ISSUE TITLE
Persistent context menu

### ISSUE THREAD

**Issue by italomarsili** [Wildhoney/ngContextMenu#43]
I have a little question. Is it possible implement a persistent ng-contextmenu?
The idea would be to open and close the context menu with a simple right-click.
I woulde prefer that context menu will not close automatically after the selection of an item.

This would be very usefull.

Thank you very much in advance.

**Comment by Wildhoney** [comment]
I suppose we could add a conditional [on this line](https://github.com/Wildhoney/ngContextMenu/blob/master/module/ngContextMenu.js#L169) to prevent it closing on click.

Are you happy to open a PR for this @italomarsili?

**Comment by italomarsili** [comment]
Thank you @Wildhoney . I would appreciate it very much but, unfortunately, I'm not so familiar with JavaScript and I would be afraid to post some mistakes. Furthermore, probably, some users don't need this specific feature of persistent ng-contextmenu.
However, if you appreciate, I may share in private with you my possible solution.

**Comment by Wildhoney** [comment]
Thank you @italomarsili 👍That sounds good to me. Please send your proposal across to me.
