### ISSUE TITLE
Adapt directive to use left (standard) click

### ISSUE THREAD

**Issue by thuna-garry** [Wildhoney/ngContextMenu#6]
I quite like the way you have structured the usage of the menu and it seems the most logical of a number that I've looked at.

I would, however, like to use it in a mobile application so I need to modify the directive to use regular click (as mobile has no right-click), but I'm still quite new to angular and can't quite see where you have bound it to the right-click.

Would you be able to point me in the right (no pun intended) direction to make this change, or possibly consider adding an config option or attribute to specify to which mouse button the click is bound?

Thanks.

**Comment by Wildhoney** [comment]
In https://github.com/Wildhoney/ngContextMenu/commit/5623c0833bf5716b493e70448b0be3dc53bb92cf I've added the `data-context-event` attribute which you can set to **any** acceptable mouse event &mdash; default is `contextmenu` if you leave it empty. In your case try and set it to `click` and see if that's what you were expecting :+1:

**Comment by thuna-garry** [comment]
Works just as you described.
Blown away that you changed it and so quickly after my query.
Thank-you.
