### ISSUE TITLE
Not working for nested element

### ISSUE THREAD

**Issue by teohjk** [Wildhoney/ngContextMenu#8]
When I do context menu on nested element,

Parent menu open up when i right click child element. Child element menu never fired.

Ex:
```
<div data-context-menu="parent-menu.html">
<ul>
<li data-context-menu="child-menu.html">Test</li>
<li>....</li>
</ul>
</div>
```
It doesn't support or is a bug? Thanks.

**Comment by Wildhoney** [comment]
Thanks for raising the bug! `event.stopPropagation()` should have fixed this :+1: Please try again.

**Comment by teohjk** [comment]
Great. It works. Thanks.
