### ISSUE TITLE
Cannot add expressions to context menu

### ISSUE THREAD

**Issue by xenit-raven** [Wildhoney/ngContextMenu#9]
I've created a context menu and added a controller. Excecuting functions works fine but resolving expressions doesn't.

    <ul class="menu" ng-controller="ContextmenuController as cmc">
        <li class="title">Available actions:</li>
        <li><a ng-href="{{cmc.url}}">Download</a></li>  // resolves to <a href>
        <li><a ng-href="{{cmc.getUrl()}}">Download (2)</a></li> // resolves to <a href>
        <li><md-button ng-click="cmc.printDebug()">Debug</md-button></li> // works
    </ul>

**Comment by Wildhoney** [comment]
Hmm. Tough one. I've modified it so it takes into account the `ng-controller` attribute, but you'll need to add it to where you define your `data-context-menu` attribute:

```html
<ul class="messages">

        <li class="message" ng-controller="MessageController as mc"
                            ng-repeat="message in messages"
                            ng-model="message"
                            data-context-event="contextmenu"
                            data-context-menu="context-menus/message.html">

            <h2 data-context-menu="context-menus/subject.html"><a href="#">{{message.subject}}</a></h2>
            <div class="sent">Sent by {{message.from}} on {{message.date | date: "dd MMM yy"}}</div>

        </li>

    </ul>
```

**Comment by xenit-raven** [comment]
Not sure what's going on with this version, but every time I open the contextmenu I trigger a loop in angular:

![maximum call stack size exceeded](https://cloud.githubusercontent.com/assets/10155219/7227329/24059f50-e750-11e4-9ca1-85138f752a04.png)

Reverting to the previous version clears this issue. I'm using Angular 1.4.0-beta.5 (Updating to 1.4.0-rc.0 soon). 

The only adjustments I've made to the source was the following block

    // Update the position of the newly added context menu.
    scope.menu    = $angular.element(nativeElement.childNodes[childCount - 1]);
    var posX = event.clientX;
    var posY = event.clientY;
    var maxX = event.view.innerWidth - scope.menu.width();
    var maxY = event.view.innerHeight - scope.menu.height();
    scope.menu.css({ left: Math.min(posX, maxX) });
    scope.menu.css({ top: Math.min(posY, maxY) });

**Comment by Wildhoney** [comment]
Last week I refactored this module &ndash; I've just released it as `0.3.0` so please try again now :+1: the new version uses a much saner scope handler, which should solve your issues.

**Comment by Wildhoney** [comment]
Also see the [updated example](https://github.com/Wildhoney/ngContextMenu/blob/master/example/index.html), as I've added the item controller as you are wanting it set-up.

**Comment by xenit-raven** [comment]
Just integrated this version and the controller is now working just as expected!

**Comment by Wildhoney** [comment]
:+1: 

I removed the `addEventListener` on the `document`, and instead added it in the [example controller](https://github.com/Wildhoney/ngContextMenu/blob/master/example/js/Application.js#L12) for you to implement that yourself in your own app. I'm not sure where this responsibility should be, but I'm happy to add it back into the module.

**Comment by xenit-raven** [comment]
Hah, that was a feature! I didn't notice. :D
At first glance it would make most sense for it to be built-in I think.. Plus then you don't require a $document and $scope injection in the controller.

**Comment by Wildhoney** [comment]
Hah, yep, I pulled that out from under your feet.

It's back again now... :+1:

**Comment by xenit-raven** [comment]
Thanks, that's all working now +1
